// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHsr0d_IuMjm2YDnoB36MDidqoA1hhzY',
    appId: '1:296240755283:web:f9d74c17f8547f4511cca6',
    messagingSenderId: '296240755283',
    projectId: 'financeflow-v43gz',
    authDomain: 'financeflow-v43gz.firebaseapp.com',
    storageBucket: 'financeflow-v43gz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfkOZDzzrZv0FBlbFSOgx0Blg2MEdWmBE',
    appId: '1:296240755283:android:d7725158d8f10a3d11cca6',
    messagingSenderId: '296240755283',
    projectId: 'financeflow-v43gz',
    storageBucket: 'financeflow-v43gz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6k2LBk7OxArLuyno-mlLMWTtpMkDskM',
    appId: '1:296240755283:ios:6045e62a5cbcd90611cca6',
    messagingSenderId: '296240755283',
    projectId: 'financeflow-v43gz',
    storageBucket: 'financeflow-v43gz.firebasestorage.app',
    iosBundleId: 'com.example.gigworker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6k2LBk7OxArLuyno-mlLMWTtpMkDskM',
    appId: '1:296240755283:ios:6045e62a5cbcd90611cca6',
    messagingSenderId: '296240755283',
    projectId: 'financeflow-v43gz',
    storageBucket: 'financeflow-v43gz.firebasestorage.app',
    iosBundleId: 'com.example.gigworker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHsr0d_IuMjm2YDnoB36MDidqoA1hhzY',
    appId: '1:296240755283:web:ef9e7a6ab4de75bc11cca6',
    messagingSenderId: '296240755283',
    projectId: 'financeflow-v43gz',
    authDomain: 'financeflow-v43gz.firebaseapp.com',
    storageBucket: 'financeflow-v43gz.firebasestorage.app',
  );

}