// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxld8QwyiAhAc52L4ngPod5uLCyNWe_8',
    appId: '1:1049501479506:web:34069a643ef0b2cfd4a58b',
    messagingSenderId: '1049501479506',
    projectId: 'gigworker-11830',
    authDomain: 'gigworker-11830.firebaseapp.com',
    storageBucket: 'gigworker-11830.firebasestorage.app',
    measurementId: 'G-RRSKV9XF67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9GYX_xUn-uL20alOQE3r2nVJyr_h3aLk',
    appId: '1:1049501479506:android:65528047177d6229d4a58b',
    messagingSenderId: '1049501479506',
    projectId: 'gigworker-11830',
    storageBucket: 'gigworker-11830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLq3NjNVcreH2nVrw-NT6GvW7qcheKQs',
    appId: '1:1049501479506:ios:c5fe483ad907ab1dd4a58b',
    messagingSenderId: '1049501479506',
    projectId: 'gigworker-11830',
    storageBucket: 'gigworker-11830.firebasestorage.app',
    iosClientId: '1049501479506-i1q838jaoivrmvuq7bmb5m86a89hnop2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigworker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLq3NjNVcreH2nVrw-NT6GvW7qcheKQs',
    appId: '1:1049501479506:ios:c5fe483ad907ab1dd4a58b',
    messagingSenderId: '1049501479506',
    projectId: 'gigworker-11830',
    storageBucket: 'gigworker-11830.firebasestorage.app',
    iosClientId: '1049501479506-i1q838jaoivrmvuq7bmb5m86a89hnop2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigworker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTxld8QwyiAhAc52L4ngPod5uLCyNWe_8',
    appId: '1:1049501479506:web:aba48adb6bf0af81d4a58b',
    messagingSenderId: '1049501479506',
    projectId: 'gigworker-11830',
    authDomain: 'gigworker-11830.firebaseapp.com',
    storageBucket: 'gigworker-11830.firebasestorage.app',
    measurementId: 'G-K7BZFX00E4',
  );

}